"""Added age and description to User model

Revision ID: 190f0324141b
Revises: 102017f224c5
Create Date: 2023-09-27 23:38:55.498571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190f0324141b'
down_revision = '102017f224c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('biography', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hobbies')
        batch_op.drop_column('biography')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
